### ISSUE TITLE
Run integration tests with vars-gridview.

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/annosaurus#39]
@kevinsbarnard I'm almost done a revamp of both the annosaurus and vampire-squid services. One important step is to run integration testing with VARS grid view against the changed services. If you have tests for the api calls in place, I can probably just run them and make changes. If you don't then we may have to sit down together and discuss the upcoming changes. Hopefully this won't be painful, they're should be only a few relatively minor changes.

**Comment by kevinsbarnard** [comment]
@hohonuuli I don't have unit tests for the M3 API calls in place. My inclination is to spin up the M3 services on rocinante, then test all of the read/write endpoints by running GridView. There aren't too many of them that GridView hits, so this shouldn't be too bad. Let me know whenever you'd like to chat about this!

**Comment by hohonuuli** [comment]
@kevinsbarnard vars-gridview seems to work as is.
